apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-3-deployment
  labels:
    app: backend-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-3
        image: ibsina/backend-3
        ports:
        - containerPort: 80