apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-direct-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-direct
        image: ibsina/frontend-direct 
        ports:
        - containerPort: 8080