apiVersion: v1
kind: Service
metadata:
  name: frontend-direct-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: frontend-direct 
  ports:
    - name: "http"
      port: 8080
      targetPort: 5002
      nodePort: 31083 
    - name: "ssh"
      port: 2222
      targetPort: 22
      nodePort: 31084